[log]
#日志级别 debug  info error dpanic panic
level = "debug"
#日志路径
path = "/tmp/log/dream.log"
#单个日志文件的大小
logsize = 100

[excel]
#excel 文件的导出路径
path = "/tmp/excel/"

[safe]
#用户输入限制（字符个数）
maxInputLen = 50
